const list = [
    // "http",
    // "https",
    // "www",
    // "discord",
    // "discordapp",
    // "discord.com",
    // "discordapp.com",
    // "discord.co",
    // "discord.fr",
    // "discordsez.com",
    // "discord.gg",
    // "dis.gd",
    // "dsc.gg",
    // "disboard",
    "*dyke",
    "acrotomophilia",
    "apeshit",
    "ass-fucker",
    "assbag",
    "assbanger",
    "assbite",
    "asscock",
    "asscracker",
    "assface",
    "assfucker",
    "assfukka",
    "assgoblin",
    "asshat",
    "asshead",
    "asshopper",
    "assjacker",
    "asslick",
    "asslicker",
    "assmonkey",
    "assmunch",
    "assmuncher",
    "asspirate",
    "assrammer",
    "asssucker",
    "asswad",
    "asswipe",
    "ayir",
    "baby batter",
    "baby juice",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "ballsack",
    "bampot",
    "bangbros",
    "bareback",
    "barenaked",
    "bassterds",
    "bastard",
    "bastardo",
    "bastards",
    "bastardz",
    "basterds",
    "basterdz",
    "bastinado",
    "bellend",
    "big knockers",
    "bimbos",
    "black cock",
    "blow job",
    "blow your load",
    "blowjob",
    "blowjobs",
    "blue waffle",
    "blumpkin",
    "boffing",
    "boiolas",
    "bondage",
    "boner",
    "brown showers",
    "brunette action",
    "buceta",
    "bugger",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bung hole",
    "bunghole",
    "bunny fucker",
    "butt-pirate",
    "buttcheeks",
    "buttmunch",
    "buttplug",
    "buttwipe",
    "camslut",
    "camwhore",
    "clusterfuck",
    "cnts",
    "cntz",
    "cnut",
    "cock-head",
    "cock-sucker",
    "cockbite",
    "cockburger",
    "cockface",
    "cockhead",
    "cockjockey",
    "cockknoker",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknose",
    "cocknugget",
    "cockshit",
    "cocksmith",
    "cocksmoker",
    "cocksuck",
    "cocksuck ",
    "cocksucked",
    "cocksucked ",
    "cocksucker",
    "cocksucking",
    "cocksucks ",
    "cocksuka",
    "cocksukka",
    "cokmuncher",
    "coksucka",
    "coochie",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "cumslut",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunnie",
    "cunnilingus",
    "cunt",
    "cunt*",
    "cuntface",
    "cunthole",
    "cuntlick",
    "cuntlick ",
    "cuntlicker",
    "cuntlicker ",
    "cuntlicking",
    "cuntlicking ",
    "cuntrag",
    "date rape",
    "daterape",
    "deep throat",
    "deepthroat",
    "dego",
    "dickbag",
    "dickbeater",
    "dickface",
    "dickhead",
    "dickhole",
    "dickjuice",
    "dickmilk",
    "dickmonger",
    "dickslap",
    "dicksucker",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwod",
    "fagg0t",
    "fagg1t",
    "fagging",
    "faggit",
    "faggitt",
    "faggot",
    "faggs",
    "fagit",
    "fagot",
    "fagots",
    "fagtard",
    "fagz",
    "faig",
    "faigs",
    "fanculo",
    "femdom",
    "fux0r",
    "gang bang",
    "gangbang",
    "gangbanged",
    "gangbanged ",
    "gangbangs ",
    "goo girl",
    "gooch",
    "goodpoop",
    "gook",
    "goregasm",
    "gringo",
    "grope",
    "guido",
    "guiena",
    "guro",
    "h00r",
    "h0ar",
    "h0r",
    "h0re",
    "hand job",
    "handjob",
    "heeb",
    "helvete",
    "hentai",
    "heshe",
    "hoar",
    "hoare",
    "hoe",
    "hoer",
    "hoer*",
    "hoor",
    "hoore",
    "hore",
    "how to kill",
    "how to murder",
    "huevon",
    "huge fat",
    "humping",
    "incest",
    "injun",
    "intercourse",
    "jail bait",
    "jailbait",
    "kanker*",
    "kawk",
    "kike",
    "kiunt",
    "klootzak",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "knobs",
    "knobz",
    "knulle",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kootch",
    "kraut",
    "kumer",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunt",
    "kunts",
    "kuntz",
    "kurac",
    "kurwa",
    "kusi*",
    "kyke",
    "kyrpa*",
    "labia",
    "lemon party",
    "lesbo",
    "lezzian",
    "lezzie",
    "lipshits",
    "lipshitz",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "make me come",
    "male squirting",
    "mamhoon",
    "masochist",
    "masokist",
    "menage a trois",
    "merd*",
    "mibun",
    "minge",
    "missionary position",
    "mo-fo",
    "mof0",
    "mofo",
    "monkleigh",
    "mouliewop",
    "mound of venus",
    "muff",
    "muff diver",
    "muffdiver",
    "muffdiving",
    "orospu",
    "paki",
    "pakie",
    "paky",
    "panooch",
    "paska*",
    "pawn",
    "pecker",
    "peckerhead",
    "pedobear",
    "pedophile",
    "penis-breath",
    "penisfucker",
    "picka",
    "pierdol*",
    "pigfucker",
    "pillu*",
    "pimmel",
    "pimpis",
    "pissflap",
    "pissflaps",
    "pizda",
    "poonani",
    "poonany",
    "poontang",
    "poontsee",
    "pornography",
    "pornos",
    "preteen",
    "punta",
    "quim",
    "rape",
    "raping",
    "rapist",
    "scat",
    "schaffer",
    "scheiss*",
    "schlampe",
    "schlong",
    "schmuck",
    "scissoring",
    "screwing",
    "scroat",
    "scrote",
    "scrotum",
    "semen",
    "sh1ter",
    "sh1tter",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "sharmuta",
    "sharmute",
    "shaved beaver",
    "shemale",
    "shibari",
    "shipal",
    "shiznit",
    "shota",
    "shrimping",
    "skanck",
    "skank",
    "skankee",
    "skankey",
    "skanks",
    "skanky",
    "skeet",
    "skribz",
    "skurwysyn",
    "slag",
    "slanteye",
    "slut",
    "slutbag",
    "sluts",
    "slutty",
    "slutz",
    "snowballing",
    "sodomize",
    "sodomy",
    "spac",
    "sphencter",
    "spic",
    "spick",
    "spierdalaj",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "style doggy",
    "suicide girls",
    "suka",
    "sultry women",
    "tea bagging",
    "threesome",
    "throating",
    "thundercunt",
    "tittiefucker",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "twink",
    "twinkie",
    "two girls one cup",
    "twunt",
    "twunter",
    "w00se",
    "wang",
    "wh00r",
    "wh0re",
    "whore",
    "wop*",
    "yaoi",
    "yed",
    "yellow showers",
    "zoophilia",
];

module.exports = { list };
