const list = [
    "*dyke",
    "acrotomophilia",
    "ahole",
    "amcik",
    "anilingus",
    "apeshit",
    "ass monkey",
    "ass-fucker",
    "ass-hat",
    "ass-pirate",
    "assbag",
    "assbandit",
    "assbanger",
    "assbite",
    "assclown",
    "asscock",
    "asscracker",
    "asses",
    "assface",
    "assfucker",
    "assfukka",
    "assgoblin",
    "asshat",
    "asshead",
    "asshopper",
    "assjacker",
    "asslick",
    "asslicker",
    "assmonkey",
    "assmunch",
    "assmuncher",
    "asspirate",
    "assrammer",
    "asssucker",
    "asswad",
    "asswipe",
    "ayir",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "ballsack",
    "bampot",
    "bangbros",
    "bareback",
    "barenaked",
    "bassterds",
    "bastard",
    "bastardo",
    "bastards",
    "bastardz",
    "basterds",
    "basterdz",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips",
    "bellend",
    "big knockers",
    "bimbos",
    "black cock",
    "blow job",
    "blow your load",
    "blowjob",
    "blowjobs",
    "blue waffle",
    "blumpkin",
    "boffing",
    "boiolas",
    "bondage",
    "boner",
    "brown showers",
    "brunette action",
    "buceta",
    "bugger",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bung hole",
    "bunghole",
    "bunny fucker",
    "butt-pirate",
    "buttcheeks",
    "butthole",
    "buttmunch",
    "buttplug",
    "buttwipe",
    "cabron",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cawk",
    "cawks",
    "cazzo",
    "chinc",
    "chink",
    "choad",
    "chode",
    "chraa",
    "chuj",
    "cipa",
    "circlejerk",
    "cl1t",
    "cleveland steamer",
    "clit",
    "clitface",
    "clitoris",
    "clits",
    "clover clamps",
    "clusterfuck",
    "cnts",
    "cntz",
    "cnut",
    "cock-head",
    "cock-sucker",
    "cockbite",
    "cockburger",
    "cockface",
    "cockhead",
    "cockjockey",
    "cockknoker",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknose",
    "cocknugget",
    "cockshit",
    "cocksmith",
    "cocksmoker",
    "cocksuck",
    "cocksuck ",
    "cocksucked",
    "cocksucked ",
    "cocksucker",
    "cocksucking",
    "cocksucks ",
    "cocksuka",
    "cocksukka",
    "cokmuncher",
    "coksucka",
    "coochie",
    "coochy",
    "coon",
    "coons",
    "cooter",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "cox",
    "creampie",
    "cum",
    "cumbubble",
    "cumdumpster",
    "cumguzzler",
    "cumjockey",
    "cummer",
    "cumming",
    "cums",
    "cumshot",
    "cumslut",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunnie",
    "cunnilingus",
    "cunt",
    "cunt*",
    "cuntface",
    "cunthole",
    "cuntlick",
    "cuntlick ",
    "cuntlicker",
    "cuntlicker ",
    "cuntlicking",
    "cuntlicking ",
    "cuntrag",
    "cunts",
    "cuntz",
    "date rape",
    "daterape",
    "daygo",
    "deep throat",
    "deepthroat",
    "dego",
    "dendrophilia",
    "dickbag",
    "dickbeater",
    "dickface",
    "dickhead",
    "dickhole",
    "dickjuice",
    "dickmilk",
    "dickmonger",
    "dickslap",
    "dicksucker",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwod",
    "dike",
    "dike*",
    "dingleberries",
    "dingleberry",
    "dink",
    "dinks",
    "dirsa",
    "dirty pillows",
    "dirty sanchez",
    "dlck",
    "dog style",
    "dog-fucker",
    "doggie style",
    "doggiestyle",
    "doggin",
    "dogging",
    "doggy style",
    "doggystyle",
    "dolcett",
    "dommes",
    "donkey punch",
    "donkeyribber",
    "doochbag",
    "dookie",
    "doosh",
    "double dong",
    "double penetration",
    "douche",
    "douchebag",
    "dp action",
    "dry hump",
    "duche",
    "dumbshit",
    "dumshit",
    "dupa",
    "dvda",
    "dyke",
    "dziwka",
    "eat my ass",
    "ecchi",
    "ejackulate",
    "ejaculate",
    "ejaculated",
    "ejaculates ",
    "ejaculating ",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "ekrem*",
    "ekto",
    "enculer",
    "enema",
    "eunuch",
    "f4nny",
    "faen",
    "fag",
    "fag*",
    "fag1t",
    "fagbag",
    "faget",
    "fagg",
    "fagg0t",
    "fagg1t",
    "fagging",
    "faggit",
    "faggitt",
    "faggot",
    "faggs",
    "fagit",
    "fagot",
    "fagots",
    "fags",
    "fagtard",
    "fagz",
    "faig",
    "faigs",
    "fanculo",
    "fanny",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fatass",
    "fecal",
    "feces",
    "feck",
    "fecker",
    "feg",
    "felatio",
    "felch",
    "felcher",
    "felching",
    "fellate",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "ficken",
    "figging",
    "fingerbang",
    "fisting",
    "fitt*",
    "flange",
    "flikker",
    "flipping the bird",
    "footjob",
    "foreskin",
    "fotze",
    "frotting",
    "fudge packer",
    "fudgepacker",
    "futanari",
    "futkretzn",
    "fux",
    "fux0r",
    "g-spot",
    "g00k",
    "gang bang",
    "gangbang",
    "gangbanged",
    "gangbanged ",
    "gangbangs ",
    "gayass",
    "gaybob",
    "gaydo",
    "gaytard",
    "gaywad",
    "genitals",
    "giant cock",
    "goatcx",
    "goatse",
    "gokkun",
    "golden shower",
    "goo girl",
    "gooch",
    "goodpoop",
    "gook",
    "goregasm",
    "gringo",
    "grope",
    "guido",
    "guiena",
    "guro",
    "h00r",
    "h0ar",
    "h0r",
    "h0re",
    "hand job",
    "handjob",
    "heeb",
    "helvete",
    "hentai",
    "heshe",
    "ho",
    "hoar",
    "hoare",
    "hoe",
    "hoer",
    "hoer*",
    "homoerotic",
    "honkey",
    "honky",
    "hooker",
    "hoor",
    "hoore",
    "hore",
    "how to kill",
    "how to murder",
    "huevon",
    "huge fat",
    "hui",
    "humping",
    "incest",
    "injun",
    "intercourse",
    "jack off",
    "jack-off ",
    "jackass",
    "jackoff",
    "jail bait",
    "jailbait",
    "jap",
    "japs",
    "jelly donut",
    "jerk off",
    "jerk-off",
    "jerk-off ",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jisim",
    "jism",
    "jiss",
    "jiz",
    "jiz ",
    "jizm",
    "jizm ",
    "jizz",
    "juggs",
    "kanker*",
    "kawk",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "kiunt",
    "klootzak",
    "knob",
    "knobbing",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "knobs",
    "knobz",
    "knulle",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kootch",
    "kraut",
    "kuk",
    "kuksuger",
    "kum",
    "kumer",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunt",
    "kunts",
    "kuntz",
    "kurac",
    "kurwa",
    "kusi*",
    "kyke",
    "kyrpa*",
    "labia",
    "lemon party",
    "lesbo",
    "lezzian",
    "lezzie",
    "lipshits",
    "lipshitz",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "make me come",
    "male squirting",
    "mamhoon",
    "masochist",
    "masokist",
    "massterbait",
    "masstrbait",
    "masstrbate",
    "master-bate",
    "masterb8",
    "masterbaiter",
    "masterbat*",
    "masterbat3",
    "masterbate",
    "masterbates",
    "masterbation",
    "masterbations",
    "masturbat*",
    "masturbate",
    "menage a trois",
    "merd*",
    "mibun",
    "minge",
    "missionary position",
    "mo-fo",
    "mof0",
    "mofo",
    "monkleigh",
    "mouliewop",
    "mound of venus",
    "muff",
    "muff diver",
    "muffdiver",
    "muffdiving",
    "muie",
    "mulkku",
    "muschi",
    "n1gga",
    "n1gger",
    "n1gr",
    "nambla",
    "nastt",
    "nawashi",
    "nazi",
    "nazis",
    "negro",
    "neonazi",
    "nepesaurio",
    "nig nog",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "nigger*",
    "nigger;",
    "niggers ",
    "niglet",
    "nigur;",
    "niiger;",
    "niigr;",
    "nob",
    "nob jokey",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "nsfw images",
    "nude",
    "nudity",
    "numbnuts",
    "nutsack",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "orafis",
    "orgasim",
    "orgasim ",
    "orgasim;",
    "orgasims ",
    "orgasm",
    "orgasms ",
    "orgasum",
    "orgy",
    "oriface",
    "orifice",
    "orifiss",
    "orospu",
    "p0rn",
    "packi",
    "packie",
    "packy",
    "paedophile",
    "paki",
    "pakie",
    "paky",
    "panooch",
    "paska*",
    "pawn",
    "pecker",
    "peckerhead",
    "pedobear",
    "pedophile",
    "penis-breath",
    "penisfucker",
    "picka",
    "pierdol*",
    "pigfucker",
    "pillu*",
    "pimmel",
    "pimpis",
    "pisof",
    "piss pig",
    "pissflap",
    "pissflaps",
    "pissin",
    "pissin ",
    "pissing",
    "pissoff",
    "pissoff ",
    "pisspig",
    "pizda",
    "polac",
    "polack",
    "polak",
    "pole smoker",
    "polesmoker",
    "pollock",
    "ponyplay",
    "poof",
    "poon",
    "poonani",
    "poonany",
    "poontang",
    "poontsee",
    "poop chute",
    "poopchute",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "pr0n",
    "pr1c",
    "pr1ck",
    "pr1k",
    "preteen",
    "prick",
    "pricks ",
    "pron",
    "pthc",
    "pube",
    "pubes",
    "pula",
    "pule",
    "punanny",
    "punany",
    "punta",
    "puta",
    "puto",
    "puuke",
    "puuker",
    "qahbeh",
    "queaf",
    "queef",
    "queef*",
    "queerbait",
    "queerhole",
    "quim",
    "raghead",
    "raging boner",
    "rape",
    "raping",
    "rapist",
    "rautenberg",
    "recktum",
    "rectum",
    "renob",
    "retard",
    "rimjaw",
    "rimjob",
    "rimming",
    "s&m",
    "s.o.b.",
    "sadism",
    "sadist",
    "santorum",
    "scank",
    "scat",
    "schaffer",
    "scheiss*",
    "schlampe",
    "schlong",
    "schmuck",
    "scissoring",
    "screwing",
    "scroat",
    "scrote",
    "scrotum",
    "semen",
    "sh1ter",
    "sh1tter",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "sharmuta",
    "sharmute",
    "shaved beaver",
    "shemale",
    "shibari",
    "shipal",
    "shiznit",
    "shota",
    "shrimping",
    "skanck",
    "skank",
    "skankee",
    "skankey",
    "skanks",
    "skanky",
    "skeet",
    "skribz",
    "skurwysyn",
    "slag",
    "slanteye",
    "slut",
    "slutbag",
    "sluts",
    "slutty",
    "slutz",
    "snowballing",
    "sodomize",
    "sodomy",
    "spac",
    "sphencter",
    "spic",
    "spick",
    "spierdalaj",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "style doggy",
    "suicide girls",
    "suka",
    "sultry women",
    "swastika",
    "swinger",
    "tard",
    "taste my",
    "tea bagging",
    "threesome",
    "throating",
    "thundercunt",
    "tittiefucker",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tongue in a",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "turd",
    "tushy",
    "tw4t",
    "twat",
    "twathead",
    "twatlips",
    "twatty",
    "twink",
    "twinkie",
    "two girls one cup",
    "twunt",
    "twunter",
    "w00se",
    "w0p",
    "wang",
    "wank",
    "wank*",
    "wanker",
    "wanky",
    "wetback",
    "wetback*",
    "wh00r",
    "wh0re",
    "white power",
    "whoar",
    "whore",
    "wichser",
    "willies",
    "willy",
    "wop*",
    "wrapping men",
    "wrinkled starfish",
    "xrated",
    "yaoi",
    "yed",
    "yellow showers",
    "yiffy",
    "zabourah",
    "zoophilia",
];

module.exports = { list };
