const list = [
    "*dyke",
    "*fuck*",
    "*shit*",
    "4r5e",
    "5h1t",
    "5hit",
    "@$$",
    "a55",
    "a_s_s",
    "acrotomophilia",
    "ahole",
    "amcik",
    "anal",
    "anilingus",
    "apeshit",
    "ar5e",
    "arrse",
    "arschloch",
    "arse",
    "arse*",
    "arsehole",
    "ash0le",
    "ash0les",
    "asholes",
    "ass",
    "ass monkey",
    "ass-fucker",
    "ass-hat",
    "ass-pirate",
    "assbag",
    "assbandit",
    "assbanger",
    "assbite",
    "assclown",
    "asscock",
    "asscracker",
    "asses",
    "assface",
    "assfucker",
    "assfukka",
    "assgoblin",
    "assh0le",
    "assh0lez",
    "asshat",
    "asshead",
    "asshole",
    "assholes",
    "assholz",
    "asshopper",
    "assjacker",
    "asslick",
    "asslicker",
    "assmonkey",
    "assmunch",
    "assmuncher",
    "asspirate",
    "assrammer",
    "assshole",
    "asssucker",
    "asswad",
    "asswhole",
    "asswipe",
    "auto erotic",
    "autoerotic",
    "ayir",
    "azzhole",
    "b!+ch",
    "b!tch",
    "b00b*",
    "b00bs",
    "b17ch",
    "b1tch",
    "babeland",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "balls",
    "ballsack",
    "bampot",
    "bangbros",
    "bareback",
    "barely legal",
    "barenaked",
    "bassterds",
    "bastard",
    "bastardo",
    "bastards",
    "bastardz",
    "basterds",
    "basterdz",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beastial",
    "beastiality",
    "beastility",
    "beaver cleaver",
    "beaver lips",
    "bellend",
    "bestial",
    "bestiality",
    "bi+ch",
    "bi7ch",
    "biatch",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bimbos",
    "birdlock",
    "bitch",
    "bitch*",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchin",
    "bitching",
    "black cock",
    "bloody",
    "blow job",
    "blow your load",
    "blowjob",
    "blowjobs",
    "blue waffle",
    "blumpkin",
    "boffing",
    "boiolas",
    "bollock",
    "bollock*",
    "bollocks",
    "bollok",
    "bollox",
    "bondage",
    "boner",
    "boob",
    "boobie",
    "boobs",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "booty call",
    "breasts",
    "brown showers",
    "brunette action",
    "buceta",
    "bugger",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bum",
    "bung hole",
    "bunghole",
    "bunny fucker",
    "busty",
    "butt",
    "butt-pirate",
    "buttcheeks",
    "butthole",
    "buttmunch",
    "buttplug",
    "buttwipe",
    "c0ck",
    "c0cks",
    "c0cksucker",
    "c0k",
    "cabron",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cawk",
    "cawks",
    "cazzo",
    "chinc",
    "chink",
    "choad",
    "chocolate rosebuds",
    "chode",
    "chraa",
    "chuj",
    "cipa",
    "circlejerk",
    "cl1t",
    "cleveland steamer",
    "clit",
    "clitface",
    "clitoris",
    "clits",
    "clover clamps",
    "clusterfuck",
    "cnts",
    "cntz",
    "cnut",
    "cock",
    "cock*",
    "cock-head",
    "cock-sucker",
    "cockbite",
    "cockburger",
    "cockface",
    "cockhead",
    "cockjockey",
    "cockknoker",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknose",
    "cocknugget",
    "cocks",
    "cockshit",
    "cocksmith",
    "cocksmoker",
    "cocksuck",
    "cocksuck ",
    "cocksucked",
    "cocksucked ",
    "cocksucker",
    "cocksucking",
    "cocksucks ",
    "cocksuka",
    "cocksukka",
    "cok",
    "cokmuncher",
    "coksucka",
    "coochie",
    "coochy",
    "coon",
    "coons",
    "cooter",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "cox",
    "creampie",
    "cum",
    "cumbubble",
    "cumdumpster",
    "cumguzzler",
    "cumjockey",
    "cummer",
    "cumming",
    "cums",
    "cumshot",
    "cumslut",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunnie",
    "cunnilingus",
    "cunt",
    "cunt*",
    "cuntface",
    "cunthole",
    "cuntlick",
    "cuntlick ",
    "cuntlicker",
    "cuntlicker ",
    "cuntlicking",
    "cuntlicking ",
    "cuntrag",
    "cunts",
    "cuntz",
    "d1ck",
    "d4mn",
    "dammit",
    "damn",
    "darkie",
    "date rape",
    "daterape",
    "daygo",
    "deep throat",
    "deepthroat",
    "dego",
    "dendrophilia",
    "dick",
    "dick*",
    "dickbag",
    "dickbeater",
    "dickface",
    "dickhead",
    "dickhole",
    "dickjuice",
    "dickmilk",
    "dickmonger",
    "dickslap",
    "dicksucker",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwod",
    "dike",
    "dike*",
    "dild0",
    "dild0s",
    "dildo",
    "dildos",
    "dilld0",
    "dilld0s",
    "dingleberries",
    "dingleberry",
    "dink",
    "dinks",
    "dipshit",
    "dirsa",
    "dirty pillows",
    "dirty sanchez",
    "dlck",
    "dog style",
    "dog-fucker",
    "doggie style",
    "doggiestyle",
    "doggin",
    "dogging",
    "doggy style",
    "doggystyle",
    "dolcett",
    "domination",
    "dominatricks",
    "dominatrics",
    "dominatrix",
    "dommes",
    "donkey punch",
    "donkeyribber",
    "doochbag",
    "dookie",
    "doosh",
    "double dong",
    "double penetration",
    "douche",
    "douchebag",
    "dp action",
    "dry hump",
    "duche",
    "dumbshit",
    "dumshit",
    "dupa",
    "dvda",
    "dyke",
    "dziwka",
    "eat my ass",
    "ecchi",
    "ejackulate",
    "ejaculate",
    "ejaculated",
    "ejaculates ",
    "ejaculating ",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "ekrem*",
    "ekto",
    "enculer",
    "enema",
    "eunuch",
    "f u c k",
    "f u c k e r",
    "f4nny",
    "f_u_c_k",
    "faen",
    "fag",
    "fag*",
    "fag1t",
    "fagbag",
    "faget",
    "fagg",
    "fagg0t",
    "fagg1t",
    "fagging",
    "faggit",
    "faggitt",
    "faggot",
    "faggs",
    "fagit",
    "fagot",
    "fagots",
    "fags",
    "fagtard",
    "fagz",
    "faig",
    "faigs",
    "fanculo",
    "fanny",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fatass",
    "fcuk",
    "fcuker",
    "fcuking",
    "fecal",
    "feces",
    "feck",
    "fecker",
    "feg",
    "felatio",
    "felch",
    "felcher",
    "felching",
    "fellate",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "ficken",
    "figging",
    "fingerbang",
    "fingerfuck ",
    "fingerfucked ",
    "fingerfucker ",
    "fingerfuckers",
    "fingerfucking ",
    "fingerfucks ",
    "fingering",
    "fistfuck",
    "fistfucked ",
    "fistfucker ",
    "fistfuckers ",
    "fistfucking ",
    "fistfuckings ",
    "fistfucks ",
    "fisting",
    "fitt*",
    "flange",
    "flikker",
    "flipping the bird",
    "fook",
    "fooker",
    "footjob",
    "foreskin",
    "fotze",
    "frotting",
    "fu(*",
    "fuck",
    "fuck buttons",
    "fucka",
    "fucked",
    "fucker",
    "fuckers",
    "fuckhead",
    "fuckheads",
    "fuckin",
    "fucking",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckme ",
    "fucks",
    "fucktards",
    "fuckwhit",
    "fuckwit",
    "fudge packer",
    "fudgepacker",
    "fuk",
    "fuk*",
    "fukah",
    "fuken",
    "fuker",
    "fukin",
    "fukk",
    "fukkah",
    "fukken",
    "fukker",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "futanari",
    "futkretzn",
    "fux",
    "fux0r",
    "g-spot",
    "g00k",
    "gang bang",
    "gangbang",
    "gangbanged",
    "gangbanged ",
    "gangbangs ",
    "gayass",
    "gaybob",
    "gaydo",
    "gaylord",
    "gaytard",
    "gaywad",
    "genitals",
    "giant cock",
    "goatcx",
    "goatse",
    "gokkun",
    "golden shower",
    "goo girl",
    "gooch",
    "goodpoop",
    "gook",
    "goregasm",
    "gringo",
    "grope",
    "guido",
    "guiena",
    "guro",
    "h00r",
    "h0ar",
    "h0r",
    "h0re",
    "hand job",
    "handjob",
    "hard core",
    "hardcore",
    "hardcoresex ",
    "heeb",
    "hells",
    "helvete",
    "hentai",
    "heshe",
    "ho",
    "hoar",
    "hoare",
    "hoe",
    "hoer",
    "hoer*",
    "homoerotic",
    "honkey",
    "honky",
    "hooker",
    "hoor",
    "hoore",
    "hore",
    "horniest",
    "horny",
    "hot carl",
    "hotsex",
    "how to kill",
    "how to murder",
    "huevon",
    "huge fat",
    "hui",
    "humping",
    "incest",
    "injun",
    "intercourse",
    "jack off",
    "jack-off ",
    "jackass",
    "jackoff",
    "jail bait",
    "jailbait",
    "jap",
    "japs",
    "jelly donut",
    "jerk off",
    "jerk-off",
    "jerk-off ",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jisim",
    "jism",
    "jiss",
    "jiz",
    "jiz ",
    "jizm",
    "jizm ",
    "jizz",
    "juggs",
    "kanker*",
    "kawk",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "kiunt",
    "klootzak",
    "knob",
    "knobbing",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "knobs",
    "knobz",
    "knulle",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kootch",
    "kraut",
    "kuk",
    "kuksuger",
    "kum",
    "kumer",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunt",
    "kunts",
    "kuntz",
    "kurac",
    "kurwa",
    "kusi*",
    "kyke",
    "kyrpa*",
    "l3i+ch",
    "l3itch",
    "labia",
    "leather restraint",
    "leather straight jacket",
    "lemon party",
    "lesbo",
    "lezzian",
    "lezzie",
    "lipshits",
    "lipshitz",
    "lolita",
    "lovemaking",
    "lust",
    "lusting",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "make me come",
    "male squirting",
    "mamhoon",
    "masochist",
    "masokist",
    "massterbait",
    "masstrbait",
    "masstrbate",
    "master-bate",
    "masterb8",
    "masterbaiter",
    "masterbat*",
    "masterbat3",
    "masterbate",
    "masterbates",
    "masterbation",
    "masterbations",
    "masturbat*",
    "masturbate",
    "menage a trois",
    "merd*",
    "mibun",
    "milf",
    "minge",
    "missionary position",
    "mo-fo",
    "mof0",
    "mofo",
    "monkleigh",
    "motha fucker",
    "motha fuker",
    "motha fukkah",
    "motha fukker",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked ",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking ",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "mother fukah",
    "mother fuker",
    "mother fukkah",
    "mother fukker",
    "mother-fucker",
    "motherfuck",
    "motherfucked",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "mouliewop",
    "mound of venus",
    "mr hands",
    "muff",
    "muff diver",
    "muffdiver",
    "muffdiving",
    "muie",
    "mulkku",
    "muschi",
    "mutha",
    "mutha fucker",
    "mutha fukah",
    "mutha fuker",
    "mutha fukkah",
    "mutha fukker",
    "muthafecker",
    "muthafuckker",
    "muther",
    "mutherfucker",
    "n1gga",
    "n1gger",
    "n1gr",
    "nambla",
    "nastt",
    "nawashi",
    "nazi",
    "nazis",
    "negro",
    "neonazi",
    "nepesaurio",
    "nig nog",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "nigger*",
    "nigger;",
    "niggers ",
    "niglet",
    "nigur;",
    "niiger;",
    "niigr;",
    "nimphomania",
    "nob",
    "nob jokey",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "nsfw images",
    "nude",
    "nudity",
    "numbnuts",
    "nutsack",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "orafis",
    "orgasim",
    "orgasim ",
    "orgasim;",
    "orgasims ",
    "orgasm",
    "orgasms ",
    "orgasum",
    "orgy",
    "oriface",
    "orifice",
    "orifiss",
    "orospu",
    "p0rn",
    "packi",
    "packie",
    "packy",
    "paedophile",
    "paki",
    "pakie",
    "paky",
    "panooch",
    "panties",
    "panty",
    "paska*",
    "pawn",
    "pecker",
    "peckerhead",
    "pedobear",
    "pedophile",
    "peeenus",
    "peeenusss",
    "peenus",
    "pegging",
    "peinus",
    "pen1s",
    "penas",
    "penis",
    "penis-breath",
    "penisfucker",
    "penus",
    "penuus",
    "perse",
    "phuc",
    "phuck",
    "phuk",
    "phuked",
    "phuker",
    "phuking",
    "phukked",
    "phukker",
    "phukking",
    "phuks",
    "phuq",
    "picka",
    "pierdol*",
    "pigfucker",
    "pillu*",
    "pimmel",
    "pimpis",
    "pis",
    "pises",
    "pisin",
    "pising",
    "pisof",
    "piss pig",
    "piss*",
    "pissed",
    "pisser",
    "pissers",
    "pisses ",
    "pissflap",
    "pissflaps",
    "pissin",
    "pissin ",
    "pissing",
    "pissoff",
    "pissoff ",
    "pisspig",
    "pizda",
    "playboy",
    "pleasure chest",
    "polac",
    "polack",
    "polak",
    "pole smoker",
    "polesmoker",
    "pollock",
    "ponyplay",
    "poof",
    "poon",
    "poonani",
    "poonany",
    "poontang",
    "poontsee",
    "poop chute",
    "poopchute",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "pr0n",
    "pr1c",
    "pr1ck",
    "pr1k",
    "preteen",
    "prick",
    "pricks ",
    "prince albert piercing",
    "pron",
    "pthc",
    "pube",
    "pubes",
    "pula",
    "pule",
    "punanny",
    "punany",
    "punta",
    "pusies",
    "pusse",
    "pussee",
    "pussi",
    "pussies",
    "pussy",
    "pussylicking",
    "pussys ",
    "pusy",
    "puta",
    "puto",
    "puuke",
    "puuker",
    "qahbeh",
    "queaf",
    "queef",
    "queef*",
    "queerbait",
    "queerhole",
    "quim",
    "qweir",
    "raghead",
    "raging boner",
    "rape",
    "raping",
    "rapist",
    "rautenberg",
    "recktum",
    "rectum",
    "renob",
    "retard",
    "reverse cowgirl",
    "rimjaw",
    "rimjob",
    "rimming",
    "ruski",
    "rusty trombone",
    "s hit",
    "s&m",
    "s.o.b.",
    "s_h_i_t",
    "sadism",
    "sadist",
    "santorum",
    "scank",
    "scat",
    "schaffer",
    "scheiss*",
    "schlampe",
    "schlong",
    "schmuck",
    "scissoring",
    "screwing",
    "scroat",
    "scrote",
    "scrotum",
    "semen",
    "sh1ter",
    "sh1tter",
    "sh1tz",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "sharmuta",
    "sharmute",
    "shaved beaver",
    "shemale",
    "shibari",
    "shipal",
    "shit-ass",
    "shit-bag",
    "shit-bagger",
    "shit-brain",
    "shit-breath",
    "shit-cunt",
    "shit-dick",
    "shit-eating",
    "shit-face",
    "shit-faced",
    "shit-fit",
    "shit-head",
    "shit-heel",
    "shit-hole",
    "shit-house",
    "shit-load",
    "shit-pot",
    "shit-spitter",
    "shit-stain",
    "shitass",
    "shitbag",
    "shitbagger",
    "shitblimp",
    "shitbrain",
    "shitbreath",
    "shitcunt",
    "shitdick",
    "shite",
    "shiteating",
    "shited",
    "shitey",
    "shitface",
    "shitfaced",
    "shitfit",
    "shitfuck",
    "shitfull",
    "shithead",
    "shitheel",
    "shithole",
    "shithouse",
    "shiting",
    "shitings",
    "shitload",
    "shitpot",
    "shits",
    "shitspitter",
    "shitstain",
    "shitted",
    "shitter",
    "shitters ",
    "shittiest",
    "shitz",
    "shiz",
    "shiznit",
    "shota",
    "shrimping",
    "skanck",
    "skank",
    "skankee",
    "skankey",
    "skanks",
    "skanky",
    "skeet",
    "skribz",
    "skurwysyn",
    "slag",
    "slanteye",
    "slut",
    "slutbag",
    "sluts",
    "slutty",
    "slutz",
    "smeg",
    "smegma",
    "smut",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "son-of-a-bitch",
    "spac",
    "sphencter",
    "spic",
    "spick",
    "spierdalaj",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "style doggy",
    "suck",
    "sucks",
    "suicide girls",
    "suka",
    "sultry women",
    "swastika",
    "swinger",
    "t1tt1e5",
    "t1tties",
    "tainted love",
    "tard",
    "taste my",
    "tea bagging",
    "teets",
    "teez",
    "testical",
    "testicle",
    "testicle*",
    "threesome",
    "throating",
    "thundercunt",
    "tied up",
    "tight white",
    "tittiefucker",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tongue in a",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "tub girl",
    "tubgirl",
    "turd",
    "tushy",
    "tw4t",
    "twat",
    "twathead",
    "twatlips",
    "twatty",
    "twink",
    "twinkie",
    "two girls one cup",
    "twunt",
    "twunter",
    "w00se",
    "w0p",
    "wang",
    "wank",
    "wank*",
    "wanker",
    "wanky",
    "wetback",
    "wetback*",
    "wh00r",
    "wh0re",
    "white power",
    "whoar",
    "whore",
    "wichser",
    "willies",
    "willy",
    "wop*",
    "wrapping men",
    "wrinkled starfish",
    "xrated",
    "yaoi",
    "yed",
    "yellow showers",
    "yiffy",
    "zabourah",
    "zoophilia",
];

module.exports = { list };
